import React from "react";
import "./App.css";

import Advantages from "./Components/AdvantageSection";
import Benefits from "./Components/BenefitsSection";
import FadeInFromTop from "./Components/FadeInTopAnimation";
import Reward from "./Components/RewardsSection";
import ScrollAnimation from "./Components/ScrollAnimation";
import styles from "./styles/Home.module.css";

import {
  ADVANTAGES_DATA,
  REWARDS_DATA,
  ADDED_BENEFITS_DATA,
} from "./Constants/constant";

function App() {
  return (
    <div className={styles.container}>
      <head>
        <title>Unicards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className={styles.main}>
        <div className={styles.landingWrapper}>
          <video autoPlay loop muted>
            <source src="bg_1.mp4" typeof="video/mp4" />
          </video>
          <div className={styles.header}>
            <div className={styles.uniLogo}>
              <img
                src={"/icons/logo.svg"}
                height={100}
                width={100}
                alt="Uni Cards"
              />
            </div>
            <button className={styles.payCheck}>Uni Paycheck</button>
            <div className={styles.burgerMenu}>
              <img
                src={"/icons/hamburger-menu.svg"}
                height={20}
                width={31}
                alt="hamburger"
              />
            </div>
          </div>

          <div className={styles.body}>
            <div className={styles.leftSection}>
              <div className={styles.mainText}>
                <strong>NX Wave.</strong>The next-gen credit card for those who
                love rewards.
              </div>
              <div className={styles.rewardsText}>
                <span>1% Cashback</span>
                <span>
                  <img
                    src="/icons/plus.svg"
                    height={12}
                    width={12}
                    alt="plus"
                  />
                </span>
                <span>5x Rewards</span>
                <span>
                  <img
                    src="/icons/plus.svg"
                    height={12}
                    width={12}
                    alt="plus"
                  />
                </span>
                <span>Zero Forex Markup</span>
              </div>
              <div className={styles.form}>
                <div className={styles.inputField}>
                  <input type="text" placeholder="Enter Phone Number" />
                </div>
                <button className={styles.applyNow}>Apply Now</button>
              </div>
              <div className={styles.disclaimerSection}>
                <input type="checkbox" />
                <div className={styles.disclaimer}>
                  You agree to be contacted by Uni Cards over Call, SMS, Email
                  or WhatsApp to guide you through your application.
                </div>
              </div>
              <div className={styles.applyNowMobile}>
                <div className={styles.applyNowContainer}>
                  <div className={styles.applyNowText}>Apply Now</div>
                  <div className={styles.rightArrow}>
                    <img
                      src="/icons/arrow.svg"
                      height={22}
                      width={34}
                      alt="arrow"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.rightSection}>
              <div className={styles.uniImage}>
                <img
                  src={"/images/uni_cards.png"}
                  height={373}
                  width={484}
                  alt="Uni Cards"
                />
              </div>
            </div>
          </div>
        </div>

        <div className={styles.descriptionWrapper}>
          <div className={styles.description}>
            <ScrollAnimation>
              <p>
                Earn 1% assured cashback<span> on your spends. Get</span> 5X
              </p>
            </ScrollAnimation>
            <ScrollAnimation>
              <p>
                {" "}
                more value than cashback<span> at the Uni Store. Enjoy</span>
              </p>
            </ScrollAnimation>
            <ScrollAnimation>
              <p>
                <span>round the clock</span> Whatsapp support.
                <span> And it&apos;s</span>
              </p>
            </ScrollAnimation>
            <ScrollAnimation>
              <p>
                lifetime free<span>; no joining fee, no annual charges.</span>
              </p>
            </ScrollAnimation>
            <div id="triggerPoint"></div>
          </div>
          <FadeInFromTop>
            <div className={`${styles.downArrowContainer}`}>
              <div className={styles.downArrow}>
                <img
                  src="/icons/arrow.svg"
                  height={74}
                  width={74}
                  alt="arrow"
                />
              </div>
            </div>
          </FadeInFromTop>
        </div>
        <div className={styles.rewardsContainer}>
          {REWARDS_DATA.map((data, index) => (
            <Reward
              text={data.text}
              isReversed={index % 2 !== 0}
              src={data.img}
              width={data.width}
              height={data.height}
              key={index}
            />
          ))}
          <div className={styles.rewardsTextWrapper}>
            <div className={styles.rewardsText1}>
              Lifetime <span>free.</span> No joining fee. No annual charges.
            </div>
          </div>
        </div>
        <div className={styles.advantagesWrapper}>
          <div className={styles.cicleContainer}>
            <img
              src="/images/circle.png"
              height={1000}
              width={1000}
              alt="faintcircles"
            />
          </div>
          {ADVANTAGES_DATA.map((data, index) => (
            <Advantages
              text={data.text}
              height={data.height}
              width={data.width}
              src={data.img}
              key={index}
            />
          ))}
        </div>
        <div className={styles.addedBenefitsContainer}>
          {ADDED_BENEFITS_DATA.map((data, index) => (
            <Benefits
              text={data.text}
              height={data.height}
              width={data.width}
              src={data.img}
              key={index}
            />
          ))}
        </div>
        <div className={styles.commitmentContainer}>
          <div className={styles.commitmentText}>
            At Uni, we&apos;re committed to{" "}
            <span>delivering an unmatched credit experience </span>
            for millions of Indians.
          </div>
          <div className={styles.bankPartnerText}>
            On this mission, we&apos;ve partnered with some of the best in the
            business.
          </div>
          <img
            src="/images/SBM.svg"
            height={150}
            width={150}
            alt="SBM bank logo"
          />
        </div>
        <div className={styles.disclaimerContainer}>
          <div className={styles.disclaimerText}>
            Please note that to stay compliant with RBI guidelines, we have
            discontinued Pay 1/3rd and Pay 1/2 cards for the time being.
          </div>
        </div>
        <div className={styles.downloadContainer}>
          <div>Download now to get started</div>
          <div className={styles.downloadLinksContainer}>
            <div className={styles.downloadLink}>Google Play</div>
            <div className={styles.downloadLink}>App Store</div>
          </div>
        </div>
        <div className={styles.securityContainer}>
          Uni maintains the highest level of security standards
          <img
            src={"/images/pcidss_cert.svg"}
            height={60}
            width={60}
            alt="PCI DSS Certified"
          />
        </div>
        <div className={styles.footer}>
          <div className={styles.footerInnerWrapper}>
            <div className={styles.footerInner}>
              <div className={styles.footerLogo}>UNI</div>
              <div>
                Indiqube Sigma No.3/B, Nexus {"\n"}
                Koramangala 3rd Block SBI Colony,{"\n"}
                Koramangala, Bengaluru, Karnataka 560034
              </div>
              <div>
                Contact Us: 080 68216821 {"\n"}
                Email: care@uni.club
              </div>
            </div>
          </div>
        </div>
        <div className={styles.footerLinks}>
          <div className={styles.socialLinks}>
            {["Instagram", "LinkedIn", "Twitter", "Facebook", "Careers"].map(
              (item, index) => (
                <div key={index}>{item}</div>
              )
            )}
          </div>
          <div>
            Credit Card KFS | Credit Card T&Cs | Uni T&Cs | Lending Partner TnCs
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
